[project]
name = "pylenium"
version = "0.1.0"
description = "A Playwright-like Selenium framework for Python"
authors = [
    {name = "AGDthuannguyen"}
]
readme = "README.md"
requires-python = ">=3.12,<4.0"
dependencies = [
    "selenium (>=4.48.0,<5.0.0)",
    "pyyaml (>=6.0.3,<7.0.0)",
    "python-dotenv (>=1.2.3,<2.0.0)"
]


[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"

[dependency-groups]
dev = [
    "pytest (>=9.1.1,<10.0.0)",
    "pytest-xdist (>=3.8.0,<4.0.0)",
    "allure-pytest (>=2.16.0,<3.0.0)"
]
